### ISSUE TITLE
Unable to run development version using docker compose

### ISSUE THREAD

**Issue by shankscoder** [spinspire/pocketbase-sveltekit-starter#12]
Hi,
I'm running into some trouble getting the docker development environment running.

I cloned the project and tried standing up the repo using docker compose. I updated the `.env` and other files as mentioned in the READMEs.

I'm running into this error: 

```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/go/bin/air": stat /go/bin/air: no such file or directory: unknown
```

Its downloading the `cosmtrek/air` repo but for some reason the executable isn't being found. Am I missing  a step somewhere?

I'm on a Mac M1 device, if that could be a problem.

**Comment by jkdoshi** [comment]
Thank you for the well-written issue with _most_ of the information relevant to understanding it and resolving it.

May be you forgot to mention, but I'm assuming you've copied `docker-compose.override.yml.example` to `docker-compose.override.yml`. Assuming that's true, I think there's a weird bug in that setup. It works _only_ if override existed from the beginning and not after you've already started using `docker-compose.yml` without the override.

So here's what you have to do. Wipe out the old setup first by running `docker compose down`. This will remove all existing containers. Specifically, you want to remove the `pb` container, which can also be removed with `docker compose rm -s pb`. After this, just run `docker compose up -d` and let me know if that fixes the problem.

**Comment by jkdoshi** [comment]
Oh, and also review this step-by-step checklist ... https://github.com/spinspire/pocketbase-sveltekit-starter/issues/9#issuecomment-1378177712

**Comment by mares29** [comment]
Hi, I have the exact problem also on my m1 Mac. I tried your described steps but with the same error. 

Thanks for your effort.

**Comment by shankscoder** [comment]
So, to close this issue out, I just tried this again from scratch, and got this working.

I followed @jkdoshi's instructions, followed the checklists, and ensured that the docker compose files and env files were configured BEFORE the first time I ran `docker compose up`. 

The only thing I did different was I degitted the repo, removed the sveltekit app from docker-compose, and tried to standup only pocketbase.

I'll close this for now, but update this thread when I re-connect sveltekit and verify the whole repo works OOTB.

Thanks for the inputs.

**Comment by jkdoshi** [comment]
> Hi, I have the exact problem also on my m1 Mac. I tried your described steps but with the same error.
> 
> Thanks for your effort.

@mares29 does your problem still persist? Did you follow the instructions for using the override file before re-creating containers?

**Comment by jkdoshi** [comment]
> The problem was missing PWD variable in `.env`.

You're not supposed to set `PWD` environment variable by hand in `.env` file. It's an automatic variable provided by the shell whose value is always equal to the path-of-working-directory (P.W.D.)

> Based on instructions I assume when using docker, I just use compose up and then should be able to connect to pb/sk ports but that's not the case

Docker works very differently between Mac and Linux. Mac runs Docker containers in a separate Linux VM. I don't have a Mac, so I'm only guessing here. One would have to understand Mac+Docker networking fully.

My only suggestion would be to **_merge_** the following into `docker-compose.override.yml`

```
...
services:
  pb:
    ports:
      - 8090:8090
  sk:
    ports:
      - 5173:5173
```

The above will make PocketBase available at http://localhost:8090 and SvelteKit Dev available at http://localhost:5173

Please read the [original issue description](#issue-1549054799) again. As I mentioned in my [first comment](#issuecomment-1397118971), it is very well written.

- It describes the steps taken
- It quotes the exact error message
- It even mentions that they are on M1 Mac

All these things help others understand (and perhaps reproduce) the issue and come up with intelligent guesses as to what the problem might be and how to fix it.

At this point, it seems your issues is different from (this) original issue. So I'd say open a new issue following the above best practices.
