### ISSUE TITLE
/api/hello 404

### ISSUE THREAD

**Issue by YCF** [spinspire/pocketbase-sveltekit-starter#7]
at /backend
```golang
go run main.go serve
```
when i visited `/api/hello` return :
```
Hello world!
```

after `npm run build`,at /frontend
```
npm run dev:backend
npm run dev
```
when i visited `/api/hello` return :
```json
{"code":404,"message":"Not Found.","data":{}}
```

**Comment by jkdoshi** [comment]
Make sure `frontend/.env` file contains the correct setting for `PUBLIC_BACKEND` (e.g. http://127.0.0.1:8090)
