### ISSUE TITLE
How to hot reload the frontend and backend at the same time?

### ISSUE THREAD

**Issue by YCF** [spinspire/pocketbase-sveltekit-starter#8]
I found I have to build the frontend first before i run `npm run dev:backend`,
but when i builded the frontend,I editing the frontend's code ,It may not change at the same time.
```
"dev:backend": "cd ../backend && air serve --publicDir=../frontend/build",
```

**Comment by jkdoshi** [comment]
This is totally possible.

* No need to bundle the frontend
* in the `frontend` directory, run the backend with `npm run dev:backend`. This runs the backend with `air`, which allows hot reloading of the backend code changes.
* in another shell in the `frontend` directory, run `npm run dev`. This runs the SvelteKit frontend in DEV mode.
* Now hit localhost:5173 (hit the frontend, not the backend). The frontend vite is configured to proxy to backend for all paths starting with `/api`

The above should give you what you need.
