### ISSUE TITLE
hot reload both (frontend and backend) using docker-compose.yaml file

### ISSUE THREAD

**Issue by ghost** [spinspire/pocketbase-sveltekit-starter#9]
Trying to create a docker-compose.yaml file to run/build both frontend and backend Dockerrun files in hot reload without the need for any manual commands intervention.

Kindly let me know if can help out :)

**Comment by jkdoshi** [comment]
Thank you for offering to help.

Take a look at the latest [git-pushed version](https://github.com/spinspire/pocketbase-sveltekit-starter/commit/5680e4c8927b6661b702978750fa37b532dada8e).

Also, walk through this checklist first before you start.

- [ ] Start from a fresh git-cloned directory
- [ ] Read the three REAMD.md files
- [ ] copy both the `.env.example` to `.env` files and edit them
- [ ] most important:  `frontend/.env`'s `PUBLIC_BACKEND` setting should point to your PocketBase base URL (in a dockerized setup this is `http://pb:8090`)
- [ ] FOR PROD build/execute - just use the `docker-compose.yml` (without `docker-compose.override.yml`)
- [ ] FOR LIVE DEV - `cp docker-compose.override.yml.example docker-compose.override.yml` and then review/edit the override file

Please give this a try and let me know if you face any problems.
